workspace:
  base: /go
  path: src/github.com/hellvesper/arduino-cli

pipeline:
  build:
    image: golang:latest
    commands:
      - go build
      - go test -v ./... -race
    secrets: [TEST_USERNAME, TEST_PASSWORD]
